[book]
authors = ["David Lawrence Campbell"]
description = "My very own personal website."
language = "en"
multilingual = false
src = "src"
title = "David Lawrence Campbell"

[output.html]
git-repository-url = "https://github.com/dcampbell24/dcampbell24.github.io"
additional-css = ["custom.css"]
cname="dlc.name"

[build]
build-dir = "public"

[preprocessor.djot]
